In [2]:
import numpy as np

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [8]:
x.ndim

1

In [9]:
X.ndim

2

In [10]:
x.shape

(10,)

In [11]:
X.shape

(3, 5)

In [12]:
x.size

10

In [13]:
X.size

15

### numpy.array的数据访问

In [15]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[0]

0

In [17]:
x[-1]

9

In [18]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
X[0][0]

0

In [21]:
X[(2,2)]

12

In [22]:
X[2, 2]

12

In [23]:
x[0:5]

array([0, 1, 2, 3, 4])

In [25]:
x[:5]

array([0, 1, 2, 3, 4])

In [26]:
x[5:]

array([5, 6, 7, 8, 9])

In [27]:
x[::2]

array([0, 2, 4, 6, 8])

In [28]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [32]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [35]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [36]:
X[0]

array([0, 1, 2, 3, 4])

In [37]:
X[0, :]

array([0, 1, 2, 3, 4])

In [38]:
X[0, :].ndim

1

In [41]:
X[:, 0]                      # 为什么不是竖着的？

array([ 0,  5, 10])

In [40]:
X[:, 0].ndim

1

In [43]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [44]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [45]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [47]:
X[0,0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [50]:
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [51]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [52]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### reshape

In [53]:
x.shape

(10,)

In [54]:
x.ndim

1

In [55]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
B.ndim

2

In [63]:
B.shape

(1, 10)

In [64]:
x.shape

(10,)

In [65]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [66]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

### 合并操作

In [72]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [71]:
x

array([1, 2, 3])

In [73]:
y

array([3, 2, 1])

In [75]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [76]:
z = np.array([666, 666, 666])

In [77]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [79]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

In [80]:
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [83]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [84]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
A2 = np.concatenate([A, z.reshape(1, -1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [87]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [89]:
B = np.full((2,2), 100)
B

array([[100, 100],
       [100, 100]])

In [90]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [92]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions

### 分割

In [93]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
x1, x2, x3 = np.split(x, [3, 7])

In [96]:
x1

array([0, 1, 2])

In [97]:
x2

array([3, 4, 5, 6])

In [98]:
x3

array([7, 8, 9])

In [103]:
x1, x2 = np.split(x, [5])

In [104]:
x1

array([0, 1, 2, 3, 4])

In [105]:
x2

array([5, 6, 7, 8, 9])

In [106]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [107]:
A1, A2 = np.split(A, [2])

In [108]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [109]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
A1, A2 = np.split(A, [2], axis = 1)

In [111]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [112]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [114]:
upper, lower = np.vsplit(A, [2])

In [115]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [116]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
left, right = np.hsplit(A, [2])

In [118]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [119]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [120]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
X, y = np.hsplit(data, [-1])

In [122]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [123]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [124]:
y[:, 0]

array([ 3,  7, 11, 15])