In [1]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [3]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [4]:
x[3:9:2]

array([3, 5, 7])

In [5]:
[x[3], x[5], x[8]]

[3, 5, 8]

In [7]:
ind = [3, 5, 8]

In [8]:
x[ind]

array([3, 5, 8])

In [10]:
ind = np.array([[0,2],
               [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [11]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [15]:
X[0, col]

array([1, 2, 3])

In [16]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [17]:
col = [True, False, True, True]

In [18]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array的比较

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [22]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [23]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [25]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [26]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [27]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [28]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
np.sum(x<=3)

4

In [32]:
np.count_nonzero(x<= 3)

4

In [33]:
np.any(x == 0)

True

In [34]:
np.any(x < 0)

False

In [35]:
np.all(x >= 0)

True

In [36]:
np.all(x > 0)

False

In [37]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.sum(X % 2 == 0)

8

In [39]:
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [40]:
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [41]:
np.all(X>0, axis=1)

array([False,  True,  True,  True])

In [42]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
np.sum((x>3)&(x<10))     # 位运算符，不是条件运算符

6

In [44]:
np.sum((x>3)&&(x<10)) 

SyntaxError: invalid syntax (<ipython-input-44-782fd4c51103>, line 1)

In [46]:
np.sum((x%2==0)|(x>10))

11

In [47]:
np.sum(~(x==0))

15

In [48]:
x[x<5]

array([0, 1, 2, 3, 4])

In [50]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [51]:
X[X[:,3]%3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

Pandas