In [8]:
import numpy as np
from math import sqrt
from collections import Counter

def kNN_classify(k, X_train, y_train, x):
    assert 1 <= k <= X_train.shape[0], "k must be valid"
    assert X_train.shape[0] == y_train.shape[0], "the size of X_train must equal to the size of y_train"
    assert X_train.shape[1] == x.shape[0], "the feature number of x must be equal to X_train"
    
    distances = [sqrt(np.sum((x_train-x)**2)) for x_train in X_train]
    nearst = np.argsort(distances)
    
    topK_y = [y_train[i] for i in nearst[:k]]
    votes = Counter(topK_y)
    
    return votes.most_common(1)[0][0]

In [9]:
import numpy as np
np.random.seed(666)
raw_data_X = np.random.rand(20).reshape(10, -1)
np.random.seed(666)
raw_data_y = np.random.randint(0, 2, 10)

X_train = raw_data_X
y_train = raw_data_y

np.random.seed(666)
x = np.random.rand(2)

In [10]:
kNN_classify(6, X_train, y_train, x)

0

### 使用scikit-learn中的kNN

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [13]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [14]:
kNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[0.70043712 0.84418664].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [15]:
X_predict = x.reshape(1, -1)
X_predict

array([[0.70043712, 0.84418664]])

In [16]:
kNN_classifier.predict(X_predict)

array([0])

In [17]:
y_predict = kNN_classifier.predict(X_predict)
y_predict[0]

0

### 重新整理我们的kNN的代码

In [54]:
import numpy as np
from math import sqrt
from collections import Counter

class kNNClassifier:
    
    def __init__(self, k):
        """初始化kNN分类器"""
        assert k >= 1, "K must be valid!"
        self.k = k
        self._X_train = None
        self._y_train = None
        
    def fit(self, X_train, y_train):
        """根据训练数据集X_train和y_train训练kNN分类器"""
        assert X_train.shape[0] == y_train.shape[0], "the size of X_train must equal to the size of y_train"
        assert self.k <= X_train.shape[0], "the size of X_train must be at least k"
    
        self._X_train = X_train
        self._y_train = y_train
        return self
    
    def predict(self, X_predict):
        """给定待预测数据集X_predict, 返回表示X_predict的结果向量"""
        assert self._X_train is not None and self._X_train is not None, "must fit before predict"
        assert self._X_train.shape[1] == X_predict.shape[1], "the feature number of X_predict must be equal to X_train"
        
        y_predict = [self._predict(x) for x in X_predict]
        return np.array(y_predict)
    
    def _predict(self, x):
        """给定单个待测数据x，返回x的预测结果"""
        assert self._X_train.shape[1] == x.shape[0], "the feature number of x must be equal to X_train"
        
        distances = [sqrt(np.sum((x_train-x)**2)) for x_train in self._X_train]
        nearst = np.argsort(distances)
    
        topK_y = [self._y_train[i] for i in nearst[:self.k]]
        votes = Counter(topK_y)
    
        return votes.most_common(1)[0][0]
    
    def __repr__(self):
        return "KNN(k=%d)" % self.k

In [55]:
knn_clf = kNNClassifier(k=6)

In [56]:
knn_clf.fit(X_train, y_train)

KNN(k=6)

In [57]:
y_predict = knn_clf.predict(X_predict)

In [58]:
y_predict

array([0])

In [59]:
y_predict[0]

0