### 测试我们的算法

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [5]:
iris = datasets.load_iris()

In [7]:
X = iris.data
y = iris.target

In [8]:
X.shape

(150, 4)

In [9]:
y.shape

(150,)

### train_test_split

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
shuffle_indexes = np.random.permutation(len(X))
shuffle_indexes

array([ 31,  61,  82, 113, 127,  30,  63, 124,  27,  10,  18,   0,   9,
       107,  22,   6,  46, 131, 104, 148,  15,  81,  43,  47,   1,  54,
        33, 117,  76,  52,  70,   7,  41, 139, 100, 125,  56, 116,  92,
       149,  26,  24,  72, 130,  94, 119,  34,  45,  35,   3,  32, 118,
       105,  17,  73,  90,  23,  86,  64, 109,  38, 137, 132,  55, 106,
       142,  16,  68, 135,  91, 120,  51,   2,  21,  84, 102,  11,  93,
        14, 121,  74,  49,  99,  62, 101,  71,  37,   5,  75, 146, 110,
        87, 143,   8,  59,  28,  97,  83,  78,  69,  29,  88,  20, 123,
        39, 126,  85,  98,  53, 128, 145, 108,  96,  19,  44,  60,  13,
       147,  77,  40,  79,  65,  58, 141,  48,  89, 122,  95, 115, 133,
       140, 136,  50,  36,  25,  57, 103,  12, 129,  80, 144,   4,  67,
       138,  42, 112, 111, 114, 134,  66])

In [16]:
test_ratio = 0.2
test_size = int(len(x) * test_ratio)
test_size

30

In [22]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]
test_indexes

array([ 31,  61,  82, 113, 127,  30,  63, 124,  27,  10,  18,   0,   9,
       107,  22,   6,  46, 131, 104, 148,  15,  81,  43,  47,   1,  54,
        33, 117,  76,  52])

In [23]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [29]:
import numpy as np

def train_test_split(X, y, test_ratio=0.2, seed=None):
    """将X和y按照test_ratio分割成X_train，X_test，y_train，y_test"""
    
    assert X.shape[0] == y.shape[0], "the size of X must be equal to the size of y"
    assert 0.0 <= test_ratio <= 1.0, "test_ration must be valid"
    
    if seed:
        np.random.seed(seed)
        
    shuffle_indexes = np.random.permutation(len(X))
    
    test_size = int(len(x) * test_ratio)
    test_indexes = shuffle_indexes[:test_size]
    train_indexes = shuffle_indexes[test_size:]
    
    X_train = X[train_indexes]
    y_train = y[train_indexes]

    X_test = X[test_indexes]
    y_test = y[test_indexes]
    
    return X_train, X_test, y_train, y_test

### 使用我们的算法

In [30]:
 X_train, X_test, y_train, y_test = train_test_split(X, y)

In [31]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [32]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [34]:
import numpy as np
from math import sqrt
from collections import Counter

class kNNClassifier:
    
    def __init__(self, k):
        """初始化kNN分类器"""
        assert k >= 1, "K must be valid!"
        self.k = k
        self._X_train = None
        self._y_train = None
        
    def fit(self, X_train, y_train):
        """根据训练数据集X_train和y_train训练kNN分类器"""
        assert X_train.shape[0] == y_train.shape[0], "the size of X_train must equal to the size of y_train"
        assert self.k <= X_train.shape[0], "the size of X_train must be at least k"
    
        self._X_train = X_train
        self._y_train = y_train
        return self
    
    def predict(self, X_predict):
        """给定待预测数据集X_predict, 返回表示X_predict的结果向量"""
        assert self._X_train is not None and self._X_train is not None, "must fit before predict"
        assert self._X_train.shape[1] == X_predict.shape[1], "the feature number of X_predict must be equal to X_train"
        
        y_predict = [self._predict(x) for x in X_predict]
        return np.array(y_predict)
    
    def _predict(self, x):
        """给定单个待测数据x，返回x的预测结果"""
        assert self._X_train.shape[1] == x.shape[0], "the feature number of x must be equal to X_train"
        
        distances = [sqrt(np.sum((x_train-x)**2)) for x_train in self._X_train]
        nearst = np.argsort(distances)
    
        topK_y = [self._y_train[i] for i in nearst[:self.k]]
        votes = Counter(topK_y)
    
        return votes.most_common(1)[0][0]
    
    def __repr__(self):
        return "KNN(k=%d)" % self.k

In [37]:
my_Knn_clf = kNNClassifier(k = 3)

In [38]:
my_Knn_clf.fit(X_train, y_train)

KNN(k=3)

In [39]:
y_predict = my_Knn_clf.predict(X_test)

In [40]:
y_predict

array([0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0, 0, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0])

In [42]:
y_test

array([0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0])

In [44]:
sum(y_predict == y_test)

29

In [45]:
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

### sklearn中的train_test_split

In [46]:
from sklearn.model_selection import train_test_split

In [51]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [52]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [50]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [ ]:
my_Knn_clf = kNNClassifier(k = 3)
my_Knn_clf.fit(X_train, y_train)
y_predict = my_Knn_clf.predict(X_test)